# Generated by Django 5.2.12 on 2026-03-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("candidate", "Candidate"), ("employee", "Employee")],
                default="employee",
                max_length=20,
            ),
        ),
    ]
