# Generated by Django 5.2.12 on 2026-03-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_add_lesson_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="departments.department",
                    ),
                ),
                (
                    "recommended_courses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional but suggested courses.",
                        related_name="recommended_for_roles",
                        to="courses.course",
                    ),
                ),
                (
                    "required_courses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Mandatory courses for this role.",
                        related_name="required_for_roles",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "order", "title"],
            },
        ),
    ]
