# Generated by Django 5.2.12 on 2026-03-27 09:23

from django.db import migrations, models


def backfill_kb_i18n(apps, schema_editor):
    KBSection = apps.get_model("knowledge_base", "KBSection")
    Article = apps.get_model("knowledge_base", "Article")
    for obj in KBSection.objects.all():
        obj.title_en = obj.title_en or obj.title or ""
        obj.save(update_fields=["title_en"])
    for obj in Article.objects.all():
        obj.title_en = obj.title_en or obj.title or ""
        obj.content_en = obj.content_en or obj.content or ""
        obj.save(update_fields=["title_en", "content_en"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0002_article_responsible_editor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="content_ka",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="content_ru",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="title_ka",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="title_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="kbsection",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="kbsection",
            name="title_ka",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="kbsection",
            name="title_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(backfill_kb_i18n, noop),
    ]
