# Generated by Django 5.2.12 on 2026-03-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("course", "order")},
        ),
    ]
