# Generated by Django 5.2.12 on 2026-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_responsible_editor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="visible_for_candidates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="visible_for_candidates",
            field=models.BooleanField(default=False),
        ),
    ]
