# Generated by Django 5.2.12 on 2026-03-27 09:23

from django.db import migrations, models


def backfill_courses_i18n(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    Lesson = apps.get_model("courses", "Lesson")
    TestQuestion = apps.get_model("courses", "TestQuestion")
    for obj in Course.objects.all():
        obj.title_en = obj.title_en or obj.title or ""
        obj.description_en = obj.description_en or obj.description or ""
        obj.save(update_fields=["title_en", "description_en"])
    for obj in Lesson.objects.all():
        obj.title_en = obj.title_en or obj.title or ""
        obj.content_en = obj.content_en or obj.content or ""
        obj.save(update_fields=["title_en", "content_en"])
    for obj in TestQuestion.objects.all():
        obj.question_text_en = obj.question_text_en or obj.question_text or ""
        obj.options_en = obj.options_en or obj.options or []
        obj.save(update_fields=["question_text_en", "options_en"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_userprogress_candidate_quiz_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="description_ka",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="description_ru",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="course",
            name="title_ka",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="course",
            name="title_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_ka",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_ru",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_ka",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="options_en",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="options_ka",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="options_ru",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="question_text_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="question_text_ka",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="question_text_ru",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(backfill_courses_i18n, noop),
    ]
