# Generated by Django 5.2.12 on 2026-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_mentorship_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingprogram",
            name="visible_for_candidates",
            field=models.BooleanField(default=False),
        ),
    ]
