# Generated by Django 5.2.12 on 2026-03-27 09:23

from django.db import migrations, models


def backfill_onboarding_i18n(apps, schema_editor):
    OnboardingProgram = apps.get_model("onboarding", "OnboardingProgram")
    OnboardingModule = apps.get_model("onboarding", "OnboardingModule")
    OnboardingStep = apps.get_model("onboarding", "OnboardingStep")
    for obj in OnboardingProgram.objects.all():
        obj.title_en = obj.title_en or obj.title or ""
        obj.description_en = obj.description_en or obj.description or ""
        obj.save(update_fields=["title_en", "description_en"])
    for obj in OnboardingModule.objects.all():
        obj.title_en = obj.title_en or obj.title or ""
        obj.description_en = obj.description_en or obj.description or ""
        obj.save(update_fields=["title_en", "description_en"])
    for obj in OnboardingStep.objects.all():
        obj.title_en = obj.title_en or obj.title or ""
        obj.content_en = obj.content_en or obj.content or ""
        obj.save(update_fields=["title_en", "content_en"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0005_onboardingfeedback_moderation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingmodule",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingmodule",
            name="description_ka",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingmodule",
            name="description_ru",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingmodule",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="onboardingmodule",
            name="title_ka",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="onboardingmodule",
            name="title_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="onboardingprogram",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingprogram",
            name="description_ka",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingprogram",
            name="description_ru",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingprogram",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="onboardingprogram",
            name="title_ka",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="onboardingprogram",
            name="title_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="onboardingstep",
            name="content_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingstep",
            name="content_ka",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingstep",
            name="content_ru",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingstep",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="onboardingstep",
            name="title_ka",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="onboardingstep",
            name="title_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(backfill_onboarding_i18n, noop),
    ]
